//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DMAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DMAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AI HACKING
        ///engineer
        ///infiltrator
        ///CASTING TIME
        ///Action
        ///RANGE (AOE)
        ///30m
        ///DURATION
        ///C - (1 min)
        ///Target a synthetic creature within 30m. It must succeed on an Intelligence saving throw or it becomes Hacked (it is considered charmed and can&apos;t use spells or abilities). If you or creatures that are friendly to you are fighting it, it has advantage on the saving throw.
        ///
        ///On its turn, the hacked creature attacks the closest creature hostile to the spell caster, making a ranged weapon attack or melee attack if  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AllSpellInfo {
            get {
                return ResourceManager.GetString("AllSpellInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap GRID {
            get {
                object obj = ResourceManager.GetObject("GRID", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LAB {
            get {
                object obj = ResourceManager.GetObject("LAB", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mass_effect_title_screen_by_tes331_dcc3zqt_fullview {
            get {
                object obj = ResourceManager.GetObject("mass_effect_title_screen_by_tes331_dcc3zqt-fullview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string NewBattle {
            get {
                return ResourceManager.GetString("NewBattle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Features to add:
        ///Button to add premade character(s) to battle
        ///Button to save current character layout
        ///Button to retrieve saved layout
        ///Button to show only me an ability OR picture
        ///Button to auto-calc damage/hp/etc
        ///Checkboxes to add Status effects
        ///
        ///-----
        ///
        ///Important Stuff for encounter:
        ///characters and their stats
        ///who currently has initiative
        ///
        ///-----.
        /// </summary>
        internal static string Our_Notes {
            get {
                return ResourceManager.GetString("Our Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drax Nakmor;0;16;50;10;5;0;Josh
        ///Xol-44;0;16;40;10;5;0;Braden
        ///Michael Torrance;0;16;49;10;5;4;Steven
        ///Harrot;0;15;40;10;5;0;Neil
        ///KalAsari;0;14;40;10;5;3;LeAnn
        ///Gar Loco;0;14;40;10;10;0;Peter
        ///Paul;0;16;80;55;5;3;Paul.
        /// </summary>
        internal static string Party {
            get {
                return ResourceManager.GetString("Party", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drax Nakmor
        ///Xol-44
        ///Michael Torrance
        ///Harrot
        ///KalAsari
        ///Gar Loco
        ///Paul
        ///bum1
        ///bum2
        ///bum3
        ///.
        /// </summary>
        internal static string PCNames {
            get {
                return ResourceManager.GetString("PCNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to or;0;16;50;10;5;0;Joshxx
        ///-44;0;16;40;10;5;0;Bradenxx
        ///rrance;0;16;49;10;5;4;Stevenxx
        ///rot;0;15;40;10;5;0;Neilxx
        ///sari;0;14;40;10;5;3;LeAnnxx
        ///oco;0;14;40;10;10;0;Peterxx
        ///aul;0;16;80;55;5;3;Paulxx.
        /// </summary>
        internal static string TestEncounter {
            get {
                return ResourceManager.GetString("TestEncounter", resourceCulture);
            }
        }
    }
}
